import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { chmodSync, existsSync, readFileSync, mkdtempSync, mkdirSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

const repoRoot = realpathSync(new URL('..', import.meta.url));
const cli = join(repoRoot, 'bin', 'academy');
const node = process.execPath;
const surfaces = ['identity', 'role', 'knowledge', 'goals', 'priorities', 'threads', 'notes', 'dailys'];

function runCli(args, options = {}) {
  return execFileSync(node, [cli, ...args], {
    encoding: 'utf8',
    env: {
      ...process.env,
      ACADEMY_SKIP_NIGHTLY_TASK: '1',
      ...options.env,
    },
    cwd: options.cwd ?? repoRoot,
  });
}

test('plugin manifest declares Academy and points at the v3 hook config', () => {
  const manifest = JSON.parse(readFileSync(join(repoRoot, '.claude-plugin', 'plugin.json'), 'utf8'));

  assert.equal(manifest.name, 'academy');
  assert.match(manifest.description, /Academy v3/);
  assert.equal(manifest.version, '0.3.0-phase0');
  assert.equal(manifest.hooks, 'hooks/hooks.json');
});

test('hook config keeps Stop memory sync and no startup context injection hooks', () => {
  const config = JSON.parse(readFileSync(join(repoRoot, 'hooks', 'hooks.json'), 'utf8'));
  const sessionStart = config.hooks.SessionStart;
  const stop = config.hooks.Stop;

  assert.equal(sessionStart, undefined);
  assert.equal(stop.length, 1);
  assert.equal(stop[0].matcher, '*');
  assert.deepEqual(stop[0].hooks, [
    {
      type: 'command',
      command: 'node ${CLAUDE_PLUGIN_ROOT}/hooks/sync_memory.mjs',
    },
  ]);

  const serialized = JSON.stringify(config);
  assert.doesNotMatch(serialized, /inject_surface|inject_section|observe_turn|\.ops/);
});

test('memory sync hook exists as a v3 node hook, not a legacy observe hook', () => {
  const hookText = readFileSync(join(repoRoot, 'hooks', 'sync_memory.mjs'), 'utf8');

  assert.match(hookText, /syncAcademyMemory/);
  assert.doesNotMatch(hookText, /observe_turn|inject_section|haiku|gemini/i);
});

test('run launches from the project cwd with a project-local plugin dir', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  const projectDir = join(root, 'project');
  mkdirSync(projectDir);
  const resolvedProjectDir = realpathSync(projectDir);

  runCli(['create', 'kai'], { env: { AGENTS_ROOT: agentsRoot } });

  const output = runCli(['run', 'kai', '--', '-p', 'smoke'], {
    cwd: projectDir,
    env: { AGENTS_ROOT: agentsRoot, ACADEMY_DRY_RUN: '1' },
  });

  const pluginDir = join(resolvedProjectDir, '.academy', 'agents', 'kai');
  const agentDir = join(agentsRoot, 'kai');
  const promptPath = join(agentDir, '.claude', 'academy-system-prompt.md');
  assert.match(output, new RegExp(`--plugin-dir ${pluginDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
  assert.match(output, new RegExp(`--system-prompt-file ${promptPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
  assert.match(output, new RegExp(`\\[dry-run\\] cwd=${resolvedProjectDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
  assert.match(output, new RegExp(`ACADEMY_AGENT_DIR=${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
  assert.match(output, new RegExp(`ACADEMY_PROJECT_DIR=${resolvedProjectDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
});

test('create writes and run refreshes the generated system prompt from surfaces', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  const projectDir = join(root, 'project');
  mkdirSync(projectDir);

  runCli(['create', 'kai'], { env: { AGENTS_ROOT: agentsRoot } });

  const agentDir = join(agentsRoot, 'kai');
  const promptPath = join(agentDir, '.claude', 'academy-system-prompt.md');
  const initialPrompt = readFileSync(promptPath, 'utf8');

  assert.match(initialPrompt, /Generated by `academy`/);
  assert.match(initialPrompt, /Do not edit this file directly/);
  assert.equal(surfaces.every((surface) => initialPrompt.includes(`<!-- academy:surface:${surface} -->`)), true);

  writeFileSync(join(agentDir, 'identity.md'), '# Identity\n\nKai custom identity.\n');

  const output = runCli(['run', 'kai', '--', '-p', 'smoke'], {
    cwd: projectDir,
    env: { AGENTS_ROOT: agentsRoot, ACADEMY_DRY_RUN: '1' },
  });
  const refreshedPrompt = readFileSync(promptPath, 'utf8');

  assert.match(output, new RegExp(`--system-prompt-file ${promptPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
  assert.match(refreshedPrompt, /Kai custom identity/);
  assert.equal(surfaces.every((surface) => refreshedPrompt.includes(`<!-- academy:surface:${surface} -->`)), true);
});

test('create scaffolds universal skills with agent-specific paths', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  runCli(['create', 'kai'], { env: { AGENTS_ROOT: agentsRoot } });

  const agentDir = join(agentsRoot, 'kai');
  const selfUpdatePath = join(agentDir, '.claude', 'skills', 'self-update', 'SKILL.md');
  const checkInPath = join(agentDir, '.claude', 'skills', 'check-in', 'SKILL.md');
  const nightlyPath = join(agentDir, '.claude', 'skills', 'nightly-consolidation', 'SKILL.md');
  const selfUpdateText = readFileSync(selfUpdatePath, 'utf8');
  const checkInText = readFileSync(checkInPath, 'utf8');
  const nightlyText = readFileSync(nightlyPath, 'utf8');

  assert.equal(existsSync(join(agentDir, 'dreams')), true);
  assert.equal(existsSync(join(agentDir, 'memory', 'observations')), true);
  assert.equal(existsSync(join(agentDir, 'memory', 'sessions.jsonl')), true);
  assert.match(selfUpdateText, /^name: self-update/m);
  assert.match(selfUpdateText, new RegExp(`Agent home: \`${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.match(selfUpdateText, new RegExp(`identity\\.md\`: \`${join(agentDir, 'identity.md').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.match(selfUpdateText, new RegExp(`\\.claude/skills\`: \`${join(agentDir, '.claude', 'skills').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.doesNotMatch(selfUpdateText, /\{\{[a-z_]+\}\}/);

  assert.match(checkInText, /^name: check-in/m);
  assert.match(checkInText, /Check-in is kai's 1:1 protocol/);
  assert.match(checkInText, new RegExp(`Agent home: \`${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.match(checkInText, new RegExp(`Self-update skill: \`${selfUpdatePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.doesNotMatch(checkInText, /\{\{[a-z_]+\}\}/);

  assert.match(nightlyText, /^name: nightly-consolidation/m);
  assert.match(nightlyText, /Dreams directory:/);
  assert.match(nightlyText, /memory\/observations/);
  assert.match(nightlyText, /primary source/);
  assert.match(nightlyText, new RegExp(`dreams\``));
  assert.match(nightlyText, new RegExp(`This skill: \`${nightlyPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.doesNotMatch(nightlyText, /\{\{[a-z_]+\}\}/);
});

test('run backfills universal skills for existing v3 agents', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  const agentDir = join(agentsRoot, 'kai');
  const projectDir = join(root, 'project');
  mkdirSync(agentDir, { recursive: true });
  mkdirSync(projectDir);

  runCli(['run', 'kai', '--', '-p', 'smoke'], {
    cwd: projectDir,
    env: { AGENTS_ROOT: agentsRoot, ACADEMY_DRY_RUN: '1' },
  });

  const selfUpdatePath = join(agentDir, '.claude', 'skills', 'self-update', 'SKILL.md');
  const checkInPath = join(agentDir, '.claude', 'skills', 'check-in', 'SKILL.md');
  const nightlyPath = join(agentDir, '.claude', 'skills', 'nightly-consolidation', 'SKILL.md');
  const selfUpdateText = readFileSync(selfUpdatePath, 'utf8');
  const checkInText = readFileSync(checkInPath, 'utf8');
  const nightlyText = readFileSync(nightlyPath, 'utf8');

  assert.equal(existsSync(join(agentDir, 'dreams')), true);
  assert.equal(existsSync(join(agentDir, 'memory', 'observations')), true);
  assert.equal(existsSync(join(agentDir, 'memory', 'sessions.jsonl')), true);
  assert.match(selfUpdateText, /^name: self-update/m);
  assert.match(selfUpdateText, new RegExp(`Agent home: \`${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\``));
  assert.doesNotMatch(selfUpdateText, /\{\{[a-z_]+\}\}/);

  assert.match(checkInText, /^name: check-in/m);
  assert.match(checkInText, /Check-in is kai's 1:1 protocol/);
  assert.doesNotMatch(checkInText, /\{\{[a-z_]+\}\}/);

  assert.match(nightlyText, /^name: nightly-consolidation/m);
  assert.match(nightlyText, /memory\/observations/);
  assert.match(nightlyText, /primary source/);
  assert.doesNotMatch(nightlyText, /\{\{[a-z_]+\}\}/);
});

test('create registers a nightly Helm consolidation task', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  const binDir = join(root, 'bin');
  const logPath = join(root, 'helm-args.txt');
  mkdirSync(binDir);
  const helmTasks = join(binDir, 'helm-tasks');
  writeFileSync(helmTasks, `#!/usr/bin/env bash
printf '%s\\n' "$PWD" > "${logPath}"
printf '%s\\n' "$@" >> "${logPath}"
`);
  chmodSync(helmTasks, 0o755);

  const output = runCli(['create', 'kai'], {
    env: {
      AGENTS_ROOT: agentsRoot,
      ACADEMY_SKIP_NIGHTLY_TASK: '0',
      PATH: `${binDir}:${process.env.PATH}`,
      TZ: 'America/Los_Angeles',
    },
  });

  const agentDir = join(agentsRoot, 'kai');
  const helmArgs = readFileSync(logPath, 'utf8');
  assert.match(output, /Registered nightly consolidation job "kai-nightly-consolidation"/);
  assert.match(helmArgs, new RegExp(`^${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm'));
  assert.match(helmArgs, /^schedule$/m);
  assert.match(helmArgs, /^--cwd$/m);
  assert.match(helmArgs, new RegExp(`^${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm'));
  assert.match(helmArgs, /^kai-nightly-consolidation$/m);
  assert.match(helmArgs, /^0 22 \* \* \*$/m);
  assert.match(helmArgs, /^America\/Los_Angeles$/m);
  assert.match(helmArgs, /^academy$/m);
  assert.match(helmArgs, /^run$/m);
  assert.match(helmArgs, /^kai$/m);
  assert.match(helmArgs, /nightly-consolidation skill/);
});

test('run inside the agent home stays in agent-home mode', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  runCli(['create', 'kai'], { env: { AGENTS_ROOT: agentsRoot } });

  const agentDir = join(agentsRoot, 'kai');
  const output = runCli(['run', 'kai', '--', '-p', 'smoke'], {
    cwd: agentDir,
    env: { AGENTS_ROOT: agentsRoot, ACADEMY_DRY_RUN: '1' },
  });

  assert.doesNotMatch(output, /--plugin-dir/);
  assert.match(output, new RegExp(`\\[dry-run\\] cwd=${agentDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
});

test('run delegates legacy agents to their recorded academy root', () => {
  const root = mkdtempSync(join(tmpdir(), 'academy-cli-'));
  const agentsRoot = join(root, 'agents');
  const legacyRoot = join(root, 'legacy-academy');
  const legacyScripts = join(legacyRoot, 'scripts');
  const agentDir = join(agentsRoot, 'legacy');
  const projectDir = join(root, 'project');
  mkdirSync(legacyScripts, { recursive: true });
  mkdirSync(agentDir, { recursive: true });
  mkdirSync(projectDir);

  writeFileSync(join(agentDir, '.academy_root'), `${legacyRoot}\n`);
  writeFileSync(join(legacyScripts, 'agent.mjs'), `
    console.log('legacy argv=' + JSON.stringify(process.argv.slice(2)));
    console.log('legacy cwd=' + process.cwd());
  `);

  const output = runCli(['run', 'legacy', '--', '-p', 'smoke'], {
    cwd: projectDir,
    env: { AGENTS_ROOT: agentsRoot },
  });

  assert.match(output, /legacy argv=\["run","legacy","--","-p","smoke"\]/);
  assert.match(output, new RegExp(`legacy cwd=${realpathSync(projectDir).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
});
