import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { ACADEMY_ROOT, memoryBridgeEnabled, resolveExecutable, shellSingleQuote } from './core.mjs';
import { MEMORY_BRIDGE_ENV_KEYS } from '../../hooks/memory_bridge.mjs';

function codexHome() {
  return process.env.CODEX_HOME || join(homedir(), '.codex');
}

function codexProfileName(name) {
  return `academy-${name}`;
}

function tomlString(value) {
  return JSON.stringify(value);
}

export function codexRuntimeContextPath() {
  return join(codexHome(), 'academy-runtime-context.json');
}

function academyHookCommand(scriptName, contextPath) {
  return [
    'env',
    `ACADEMY_RUNTIME_CONTEXT=${shellSingleQuote(contextPath)}`,
    'node',
    shellSingleQuote(join(ACADEMY_ROOT, 'hooks', scriptName)),
  ].join(' ');
}

export function writeCodexProfile(dir, name) {
  const profileName = codexProfileName(name);
  const profilePath = join(codexHome(), `${profileName}.config.toml`);
  const knowledgeCuratorConfigPath = join(dir, '.codex', 'agents', 'knowledge-curator.toml');
  mkdirSync(dirname(profilePath), { recursive: true });
  const toml = `# Generated by Academy. This profile adds Academy runtime defaults.
sandbox_mode = "workspace-write"
approval_policy = "on-request"

[sandbox_workspace_write]
writable_roots = [${tomlString(dir)}]

[features]
hooks = true

[agents.knowledge_curator]
description = "Apply evidence-gated note graduations during Academy nightly consolidation."
config_file = ${tomlString(knowledgeCuratorConfigPath)}
`;
  writeFileSync(profilePath, toml);
  return { profileName, profilePath };
}

export function readJsonFile(path, fallback) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return fallback;
  }
}

function ensureTomlTableEnabled(toml, tableHeader) {
  const lines = toml.split('\n');
  const next = [];
  let found = false;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i] !== tableHeader) {
      next.push(lines[i]);
      continue;
    }
    found = true;
    next.push(lines[i]);
    let hasEnabled = false;
    i++;
    while (i < lines.length && !lines[i].startsWith('[')) {
      if (lines[i].trim().startsWith('enabled =')) hasEnabled = true;
      next.push(lines[i]);
      i++;
    }
    if (!hasEnabled) next.push('enabled = true');
    i--;
  }
  if (!found) {
    next.push('', tableHeader, 'enabled = true');
  }
  return next.join('\n');
}

function writeCodexHookState(entries) {
  const configPath = join(codexHome(), 'config.toml');
  let toml = existsSync(configPath) ? readFileSync(configPath, 'utf8') : '';
  if (!toml.includes('[hooks.state]')) {
    toml = `${toml.trimEnd()}\n\n[hooks.state]\n`;
  }

  for (const entry of entries) {
    const header = `[hooks.state.${tomlString(entry)}]`;
    toml = ensureTomlTableEnabled(toml, header).trimEnd();
  }

  mkdirSync(dirname(configPath), { recursive: true });
  writeFileSync(configPath, toml.trimEnd() + '\n');
}

export function writeCodexHooks(contextPath) {
  const hooksPath = join(codexHome(), 'hooks.json');
  const config = readJsonFile(hooksPath, { hooks: {} });
  config.hooks = config.hooks && typeof config.hooks === 'object' ? config.hooks : {};

  config.hooks.SessionStart = Array.isArray(config.hooks.SessionStart)
    ? config.hooks.SessionStart
    : [];
  config.hooks.Stop = Array.isArray(config.hooks.Stop) ? config.hooks.Stop : [];

  const sessionStartGroup = {
    hooks: [
      {
        _academy: 'academy-runtime-hooks-v1',
        type: 'command',
        command: academyHookCommand('register_session.mjs', contextPath),
        timeout: 30,
        statusMessage: 'Registering Academy session',
      },
    ],
  };
  const stopGroup = {
    hooks: [
      {
        _academy: 'academy-runtime-hooks-v1',
        type: 'command',
        command: academyHookCommand('sync_memory.mjs', contextPath),
        timeout: 30,
        statusMessage: 'Syncing Academy memory',
      },
    ],
  };

  const sessionStartIndex = upsertCodexHookGroup(config.hooks.SessionStart, sessionStartGroup);
  const stopIndex = upsertCodexHookGroup(config.hooks.Stop, stopGroup);

  mkdirSync(dirname(hooksPath), { recursive: true });
  writeFileSync(hooksPath, JSON.stringify(config, null, 2) + '\n');
  writeCodexHookState([
    `${hooksPath}:session_start:${sessionStartIndex}:0`,
    `${hooksPath}:stop:${stopIndex}:0`,
  ]);
  return hooksPath;
}

function upsertCodexHookGroup(groups, nextGroup) {
  const index = groups.findIndex((group) => {
    return (group?.hooks || []).some((hook) => hook?._academy === 'academy-runtime-hooks-v1');
  });
  if (index >= 0) {
    groups[index] = nextGroup;
    return index;
  }
  groups.push(nextGroup);
  return groups.length - 1;
}

function writeCodexRuntimeContext(env, contextPath) {
  // The Codex sandbox strips the ambient environment, so forward Academy's own
  // keys — plus whatever the memory bridge declares it needs, but only when the
  // bridge is switched on.
  const keys = [
    'ACADEMY_AGENT_DIR',
    'ACADEMY_AGENT_NAME',
    'ACADEMY_PROJECT_DIR',
    'HOME',
    ...(memoryBridgeEnabled() ? MEMORY_BRIDGE_ENV_KEYS : []),
  ];
  const context = {
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    env: Object.fromEntries(keys.filter((key) => env?.[key]).map((key) => [key, env[key]])),
  };
  mkdirSync(dirname(contextPath), { recursive: true });
  writeFileSync(contextPath, JSON.stringify(context, null, 2) + '\n');
}

export function launchCodex(
  args,
  { cwd, env, message, profileName, profilePath, runtimeContextPath },
) {
  console.log(message);
  const codexBin =
    process.env.ACADEMY_DRY_RUN === '1'
      ? process.env.ACADEMY_CODEX_BIN || 'codex'
      : resolveExecutable('ACADEMY_CODEX_BIN', 'codex');
  if (process.env.ACADEMY_DRY_RUN === '1') {
    console.log(`[dry-run] ${codexBin} ${args.join(' ')}`);
    console.log(`[dry-run] cwd=${cwd}`);
    console.log(`[dry-run] CODEX_PROFILE=${profileName}`);
    console.log(`[dry-run] CODEX_PROFILE_PATH=${profilePath}`);
    if (env?.ACADEMY_AGENT_DIR) console.log(`[dry-run] ACADEMY_AGENT_DIR=${env.ACADEMY_AGENT_DIR}`);
    if (env?.ACADEMY_PROJECT_DIR)
      console.log(`[dry-run] ACADEMY_PROJECT_DIR=${env.ACADEMY_PROJECT_DIR}`);
    process.exit(0);
  }
  writeCodexRuntimeContext(env, runtimeContextPath);
  const result = spawnSync(codexBin, args, { stdio: 'inherit', cwd, env });
  rmSync(runtimeContextPath, { force: true });
  if (result.error) {
    console.error(
      `[ACADEMY_RUNTIME] Failed to launch Codex at ${codexBin}: ${result.error.message}`,
    );
    process.exit(1);
  }
  process.exit(result.status ?? 0);
}

// ─────────────────────────────────────────────────────────────────────────────
// `run` — launch Claude Code against the current project via plugin mode
// ─────────────────────────────────────────────────────────────────────────────
